/* tslint:disable */
/* eslint-disable */
/**
 * Aspera on Cloud API
 * A REST API for the Files, Packages, and Admin applications in Aspera’s premier SaaS offering, [Aspera on Cloud](https://www.ibm.com/cloud/aspera) (AoC). With the Aspera on Cloud API, you can quickly and reliably send and share files of any size across a hybrid cloud environment. Using AoC, organizations can store and readily access files and folders in multiple cloud-based and on-premises storage systems.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

