import { AsperaOnCloud } from './aspera-on-cloud';

let aoc = new AsperaOnCloud({
  accessToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjIwMTgtMDYtMDZUMjI6MzU6MTQrMDA6MDAifQ.eyJ1c2VyX2lkIjoiMjc4MjgiLCJzY29wZSI6InVzZXI6YWxsIiwidXVpZCI6IjIxMDE3NzdkLTc3MjMtNDcwYS1iNTQ4LTJmMDU2NWZhNjQ4OCIsIm9yZ2FuaXphdGlvbl9pZCI6IjU4IiwiZXhwaXJlc19hdCI6IjIwMjEtMDUtMjFUMDI6MjQ6MTJaIiwiZXhwIjoxNjIxNTYzODUyLCJzdWIiOiJkd29za0B1cy5pYm0uY29tIiwibmFtZSI6IkRBVklEIFdPU0siLCJnaXZlbl9uYW1lIjoiREFWSUQiLCJmYW1pbHlfbmFtZSI6IldPU0siLCJhdWQiOiJWbW9zY2cwcTh3IiwiaWF0IjoxNjIxNDc3NDUyLCJpc3MiOiJodHRwczovL2FwaS5pYm1hc3BlcmEuY29tL2FwaS92MS9vYXV0aDIvdG9rZW4iLCJpYm1pZF9pZCI6IklCTWlkLTUwUkRXMjA2SlQiLCJpZCI6ImFvYy0yNzgyOCIsInJlYWxtaWQiOiJhb2MtaWJtaWQiLCJpZGVudGlmaWVyIjoiMjc4MjgiLCJncm91cF9pZHMiOlsiMjQyNiIsIjM2MTIiLCI5NzQ3MiIsIjE5NjY3OSIsIjIyOTQ4NCIsIjIyOTQ4NSIsIjIyOTQ4NiIsIjIyOTY2MiIsIjIyOTQ4MiIsIjIzNzU5NCIsIjIzNzYwMSIsIjc3MDA2IiwiMTEwODYwIiwiMTEwODYxIiwiNzcwMTAiLCI5NzQ3MSIsIjIzNzU5NiIsIjIzNzYwMiIsIjIzNzYwMyJdLCJvcmdfYXBwcyI6WyJmaWxlcyIsInBhY2thZ2VzIl19.nb_0xnNKSnrzSLnCM4bl_loXuf6-HrszVciKr4J3Ka-c3bpqZsx2_S9WEigbrA2stKP1z73LR9LCG8Y-OvJxKneCMIZAwV2j9M-MWHxiidFdSygh9f4_dtm1JzXXXm4csAGmVcSF8lRz8TJCq9ohLjaGcN-dQi22HX15ajfQ6AfcztQUeeAlV-4IKX7DnJJP2G9nGShyqHqpC8L87qTPGrc8D9ccZSIyHtJZtyUxQHPsS9euPyPGIouhStZzVq3X6RxpsJfEsDoxkKjVrpu8ihZgFiThXwQzAWQNc-xufwKaNuCk8269mRlZNfW0o1XinjM4W1PnNoPCSfBGXufuKg",
  apiServer: 'api.qa.ibmaspera.com'
});

aoc.api.users.getUsers();

const res = aoc.getSelf();
res.then(
  user => {
    console.log(user.status);
    console.log(user.data.ats_admin);
  }
)
